---
title: "Workflow"
output: html_notebook
---

```{r, include=FALSE}
source("../../R/clean.R")
source("../../R/shape.R")
source("../../R/isolate.R")
source("../../R/model.R")
source("../../R/draw.R")
source("../../R/util.R")

load("../../data/hourly_rain.RData")
load("../../data/hourly_flow.RData")
# 
library(dplyr)
library(zoo)
library(lubridate)
library(vars)
library(imputeTS)
library(stringr)
library(tidyr)
library(ggplot2); theme_set(theme_bw())
```

##Workflow:

### Load Data
 
 - date, *defined*
 - flow, *defined*
 - rain, *defined*
 
### Scrub Data

 - scrub, cleaned

### Dry-Weather Flow

 - gwi
 - gwi_model
 - bsf
 - bsf_model
 
### Wet-Weather Flow

 - rdi
 - rdi_model
 
### Final Model

 - model
 - residual
 - error

## Example

### Load Data
```{r}
rain_ <- hourly_rain %>%
  filter(station=="BUCKMN")


tmp <- hourly_flow %>%
  filter(str_detect(location, "Pom")) %>%
  mutate(date=date(datehour)) %>%
  filter(date>mdy("10/5/2018")) %>% 
  filter(date<mdy("01/01/2020")) %>%
  left_join(rain_, by=c("datehour"="datetime"))
  

date <- tmp$datehour
flow <- tmp$flow
rain <- tmp$rainfall_in

hf <- data.frame(datetime=date, flow=flow, rain=rain)
```
### Night-Time Flow
Assume GWI is 80% of Night-Time Flow
```{r}
hf$scrub <- remove_outliers(hf$flow)

hf$gwi <- isolate_hourly_gwi(hf$datetime, hf$scrub, hf$rain)

diurnal <- isolate_hourly_dwf(hf$datetime, hf$scrub-hf$gwi, hf$rain)

hf$bsf <- isolate_hourly_bsf(hf$datetime, hf$scrub, hf$rain, diurnal)

uh <- shape_hourly_hydrograph(
    hf$datetime
  , hf$scrub-hf$gwi-hf$bsf
  , hf$rain
  , 24
  , 0.1
  , 1)

hf$rdi <- model_hydrograph(hf$rain, uh)

hf$model <- hf$bsf+hf$gwi+hf$rdi

draw_ii(hf$datetime, hf$scrub, hf$gwi, hf$model, diurnal, uh, tmp$location[1])
```
